seed: 7338
model:
  name: hf_offline_lm
  beta1: 1
  beta2: 0.01
  eta: 0
  distributional_value_learning: true
  top_n_logits: 50
  loss_type: value_learning
  pretrained: true
  init_device: mixed
  use_auth_token: true
  use_flash_attention_2: true
  pretrained_model_name_or_path: /ba420/ba420

loggers:
  mlflow:
    tracking_uri: databricks
    experiment_name: offline_apo_synth_v1_420ba

callbacks:
  offline_rl: {}
  lr_monitor: {}
  scheduled_gc:
    batch_interval: 2000
  speed_monitor:
    window_size: 10
  memory_monitor: {}
  hf_checkpointer:
    overwrite: true
    precision: bfloat16
    save_folder: s3://data-force-one-datasets/mosaicml-internal-checkpoints/owenoertell/models/{run_name}
    save_interval: 1ep

optimizer:
  lr: 1.0e-06 #7.0e-07
  eps: 1.0e-10
  name: decoupled_adamw
  betas:
  - 0.9
  - 0.95
  weight_decay: 1.0e-8
precision: amp_bf16
scheduler:
  name: cosine_with_warmup
  alpha_f: 0.05
  t_warmup: 0.02dur

tokenizer:
  name: /ba420/ba420
  kwargs:
    trust_remote_code: true
    padding_side: right

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1
eval_first: false

variables:
  reference_model:
    name: hf_offline_lm
    pretrained: true
    init_device: mixed
    use_auth_token: true
    use_flash_attention_2: true
    pretrained_model_name_or_path: /ba420/ba420

fsdp_config:
  verbose: false
  cpu_offload: false
  mixed_precision: PURE
  state_dict_type: sharded
  forward_prefetch: true
  backward_prefetch: BACKWARD_PRE
  limit_all_gathers: true
  sharding_strategy: FULL_SHARD
  activation_cpu_offload: false
  activation_checkpointing: true
  activation_checkpointing_reentrant: false

max_seq_len: 5000 #65536 #35000 #16384 #65K does not work due to oom.
dist_timeout: 3600
max_duration: 4ep
autoresume: true
progress_bar: false
train_loader:
  name: offline
  dataset:
    local: /tmp/dataset/
    split: synthetic_rollouts_from_sft_v1_420ba
    remote: dbfs:/Volumes/datasets/owenoertell/data/karl/rl_datasets/Qwen3-4B-Instruct-2507/
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: 7338
    download_retry: 4
    download_timeout: 600
  drop_last: false
  num_workers: 8
save_folder: s3://data-force-one-datasets/mosaicml-internal-checkpoints/owenoertell/qwen3-4b-sft-synth-v1-420ba-offline-apo/{run_name}

save_overwrite: True
eval_interval: 1ep
save_interval: 1ep
log_to_console: true
python_log_level: debug
load_weights_only: true
console_log_interval: 5ba
device_eval_batch_size: 1
eval_subset_num_batches: -1
global_train_batch_size: 256
device_train_microbatch_size: 1